[package]
name = "RustySpace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
cxx = "1.0.62"
winapi = "0.3.9"


[build-dependencies]
cxx-build = "1.0.62"
