[package]
name = "orbiter-rs"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Antony"]

[dependencies]
cxx = "1.0.62"

[build-dependencies]
cxx-build = "1.0.62"

[[example]]
name = "Surveyor"
path = "examples/surveyor.rs"
crate-type = ["cdylib"]
