name: cargo-publish-crate
on:
  push:
    tags:
      - v*
jobs:
  cargo-publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: deploy
          args: --dry-run
